### ISSUE TITLE
_dirname is not defined in NPM postinstall

### ISSUE THREAD

**Issue by muuvmuuv** [Arkweid/lefthook#87]
Seem slike someone forgot one underscore here: https://github.com/Arkweid/lefthook/blob/master/.npm/postinstall.js#L18

```
/Users/marvinheilemann/.npm/_npx/8422/lib/node_modules/@arkweid/lefthook/postinstall.js:18
  binpath = join(_dirname, 'bin', binary);
                 ^

ReferenceError: _dirname is not defined
    at Object.<anonymous> (/Users/marvinheilemann/.npm/_npx/8422/lib/node_modules/@arkweid/lefthook/postinstall.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @arkweid/lefthook@0.6.4 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @arkweid/lefthook@0.6.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marvinheilemann/.npm/_logs/2019-11-09T12_38_14_448Z-debug.log
Die Installation von @arkweid/lefthook@latest ist mit dem Code 1 fehlgeschlagen
```

This prevents me from updating/installing my project deps (Angular project).

**Comment by Arkweid** [comment]
Thanks! _postinstall.js_ reverted, package republished
